CREATE TABLE TENANT_INFO
(
    TENANT_INFO_ID           RAW(16)              NOT NULL,
    TENANT_ID                VARCHAR2(255)        NOT NULL,
    NAME                     VARCHAR2(255)        NOT NULL,
    CREATE_USER              VARCHAR2(32)         NOT NULL,
    CREATE_DATE              DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_USER              VARCHAR2(32)         NOT NULL,
    UPDATE_DATE              DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT TENANT_INFO_PK PRIMARY KEY (TENANT_INFO_ID)
);

ALTER TABLE TENANT_INFO
    ADD CONSTRAINT UQ_TENANT_INFO_TENANT_ID UNIQUE (TENANT_ID);

ALTER TABLE TENANT_ACCESS
    ADD CONSTRAINT FK_TENANT_ACCESS_TENANT_ID FOREIGN KEY (TENANT_ID) REFERENCES TENANT_INFO (TENANT_ID);
