ALTER TABLE DIGITAL_IDENTITY
DROP COLUMN AUTO_MATCHED;

ALTER TABLE DIGITAL_IDENTITY
ADD (
    AUTO_MATCHED_DATE TIMESTAMP
    );
COMMENT ON COLUMN DIGITAL_IDENTITY.AUTO_MATCHED_DATE IS 'This column contains the date the digital identity has been auto matched';
