GRANT SELECT ON ACCESS_CHANNEL_CODE TO PEN_READONLY;
GRANT SELECT ON DIGITAL_ID_EVENT TO PEN_READONLY;
GRANT SELECT ON DIGITAL_ID_SHEDLOCK TO PEN_READONLY;
GRANT SELECT ON DIGITAL_IDENTITY TO PEN_READONLY;
GRANT SELECT ON FLYWAY_SCHEMA_HISTORY TO PEN_READONLY;
GRANT SELECT ON IDENTITY_TYPE_CODE TO PEN_READONLY;
