---
apiVersion: v1
kind: Template
labels: 
  template: digitalid-api-pipeline-template
metadata: 
  name: digitalid-api-pipeline-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "digitalid-api-pipeline"
  spec:
    source:
      git:
        ref: feature/buildChaining
        uri: "https://github.com/bcgov/EDUC-DIGITALID-API"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/Jenkinsfile-api
