kind: "BuildConfig"
apiVersion: "v1"
metadata: 
  name: "pen-api-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/ndenny/EDUC-PEN-API"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift/Jenkinsfile/Jenkinsfile-master