---
apiVersion: v1
kind: Template
labels: 
  template: pen-api-pipeline-template
metadata: 
  name: pen-api-pipeline-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "pen-api-pipeline"
  spec:
    source:
      git:
        uri: "https://github.com/bcgov/EDUC-PEN-API"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: openshift/Jenkinsfile/Jenkinsfile-master