kind: "BuildConfig"
apiVersion: "v1"
metadata: 
  name: "pen-api-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/bcgov/EDUC-PEN-API"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: tools/openshift/api-jenkinsfile.bc.yaml