---
apiVersion: template.openshift.io/v1
kind: Template
labels:
    template: "${REPO_NAME}-template"
metadata:
    name: "${REPO_NAME}-${BRANCH}-dc"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: "${APP_NAME}-${BRANCH}"
    name: "${APP_NAME}-${BRANCH}"
  spec:
    replicas: ${{MIN_REPLICAS}}
    selector:
      app: "${APP_NAME}-${BRANCH}"
      deploymentConfig: "${APP_NAME}-${BRANCH}"
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: digitalidapi
          prometheus.io/path: /actuator/prometheus
          prometheus.io/port: '8080'
          prometheus.io/scrape: 'true'
        labels:
          app: "${APP_NAME}-${BRANCH}"
          deploymentConfig: "${APP_NAME}-${BRANCH}"
      spec:
        containers:
        - image: docker-registry.default.svc:5000/${NAMESPACE}/${REPO_NAME}-${BRANCH}:${TAG}
          imagePullPolicy: Always
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/tls-certs"
              readOnly: true
            - name: log-storage
              mountPath: /logs
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 20
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          name: "${APP_NAME}-${BRANCH}"
          ports:
          - containerPort: ${{CONTAINER_PORT}}
            protocol: TCP
          resources:
            requests:
              cpu: "${MIN_CPU}"
              memory: "${MIN_MEM}"
            limits:
              cpu: "${MAX_CPU}"
              memory: "${MAX_MEM}"
        - image: fluent/fluent-bit
          name: "${APP_NAME}-${BRANCH}-fluent-bit-sidecar"
          imagePullPolicy: Always
          volumeMounts:
            - name: log-storage
              mountPath: /mnt/log
            - name: flb-sc-config-volume
              mountPath: /fluent-bit/etc/
          readinessProbe:
            tcpSocket:
              port: 2020
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 2020
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: 2020
              protocol: TCP
              name: metrics
          resources:
            requests:
              cpu: "5m"
              memory: "25Mi"
            limits:
              cpu: "10m"
              memory: "50Mi"
        volumes:
          - name: tls-certs
            secret:
              secretName: digitalid-api-cert
          - name: log-storage
            emptyDir: {}
          - name: flb-sc-config-volume
            configMap:
              name: "${APP_NAME}-flb-sc-config-map"
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: "digitalid-api-cert"
    labels:
      app: "${APP_NAME}-${BRANCH}"
    name: "${APP_NAME}-${BRANCH}"
  spec:
    ports:
    - name: ${CONTAINER_PORT}-tcp
      port: ${{CONTAINER_PORT}}
      protocol: TCP
    selector:
      app: "${APP_NAME}-${BRANCH}"
      deploymentconfig: "${APP_NAME}-${BRANCH}"
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    name: "${APP_NAME}-${BRANCH}-cpu-autoscaler"
  spec:
    scaleTargetRef:
      apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: "${APP_NAME}-${BRANCH}"
      subresource: scale
    minReplicas: ${{MIN_REPLICAS}}
    maxReplicas: ${{MAX_REPLICAS}}
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 200
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: BRANCH
  description: Job identifier (i.e. 'backend' OR 'frontend')
  required: true
- name: NAMESPACE
  description: Target namespace reference (i.e. 'k8vopl-dev')
  required: true
- name: APP_NAME
  description: Application name
  required: true
- name: CONTAINER_PORT
  description: The port on which the application will be accessible
  value: "8080"
  required: false
- name: TAG
  description: The identifying tag for this specific deployment
  required: true
- name: MIN_REPLICAS
  description: The minimum amount of replicas
  required: true
- name: MAX_REPLICAS
  description: The maximum amount of replicas
  required: true
- name: MIN_CPU
  description: The minimum amount of cpu
  required: true
- name: MAX_CPU
  description: The maximum amount of cpu
  required: true
- name: MIN_MEM
  description: The minimum amount of memory
  required: true
- name: MAX_MEM
  description: The maximum amount of memory
  required: true
