---
apiVersion: v1
kind: Template
labels:
  template: 'api-template'
metadata:
  name: 'api-template'
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    name: openjdk-8-rhel8
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.redhat.io/openjdk/openjdk-8-rhel8:latest
      from:
        kind: DockerImage
        name: registry.redhat.io/openjdk/openjdk-8-rhel8:latest
      generation:
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: educ-pen-api
    name: educ-pen-api
    namespace: c2mvws-tools
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: 
    output:
      to:
        kind: ImageStreamTag
        name: 'educ-pen-api:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: api
      git:
        ref: master
        uri: 'https://github.com/bcgov/EDUC-PEN-API'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'openjdk-8-rhel8:latest'
      type: Source
