---
apiVersion: v1
kind: Template
labels:
  template: '${REPO_NAME}-template'
metadata:
  name: '${REPO_NAME}-bc'
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp:
      labels:
        build: "${REPO_NAME}"
      name: "${REPO_NAME}"
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp:
      labels:
        build: "${REPO_NAME}"
      name: "${REPO_NAME}"
    spec:
      completionDeadlineSeconds: 1200
      successfulBuildsHistoryLimit: 3
      failedBuildsHistoryLimit: 3
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: "${REPO_NAME}:latest"
      postCommit: {}
      resources:
        requests:
          cpu: 100m
          memory: 2Gi
        limits:
          cpu: 1000m
          memory: 4Gi
        runPolicy: SerialLatestOnly
      source:
        git:
          ref: "${SOURCE_REPO_REF}"
          uri: "${SOURCE_REPO_URL}"
        type: Git
      strategy:
        dockerStrategy:
          env:
            - name: BUILD_LOGLEVEL
              value: '2'
        type: Docker
parameters:
  - name: REPO_NAME
    description: Application repository name
    required: true
  - name: JOB_NAME
    description: Job identifier (i.e. 'pr-5' OR 'master')
    required: true
  - name: SOURCE_REPO_REF
    description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
    required: true
  - name: SOURCE_REPO_URL
    description: Git Repository URL
    required: true