---
apiVersion: v1
kind: Template
labels: 
  template: digitalid-api-pipeline
metadata: 
  name: digitalid-api-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "digitalid-api-pipeline"
  spec:
    source:
      git:
        ref: master
        uri: 'https://github.com/bcgov/EDUC-DIGITALID-API'
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/Jenkinsfile-api